version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
    networks:
      - spring-network

  springboot-mysql-docker:
    build:
      context: ./spring-boot-data-jpa-mysql-master
    image: springboot-mysql-docker
    container_name: springboot-mysql-docker
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306
    networks:
      - spring-network

  angular-app:
    build:
      context: ./angular-16-crud-example-master
    image: angular-image
    container_name: angular-container
    ports:
      - "8081:80"
    networks:
      - spring-network
    depends_on:
      - springboot-mysql-docker

networks:
  spring-network:
    driver: bridge
